services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
      POSTGRES_DB: survey
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: