services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey
      POSTGRES_DB: survey
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://survey:survey@db:5432/survey
    depends_on:
      - db

volumes:
  db_data: